import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import LoginScreen from "@/app/LoginScreen";
import Header from "./Header";
import { Toaster } from "@/components/ui/sonner";

// Here are some font styles for text content inside our app

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Here is the metadata of our app for which it helps in ranking our app on google and for better search engine optimisation

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // getServerSession : NextAuth function that lets you check if a user is logged in or not(authenticated) on the server side.

  // authOptions : These are your NextAuth configuration options (like providers, callbacks, secret, etc.)

  const session = await getServerSession(authOptions);

  // console.log({session})

  // If the user is logged in, this will contain their session data (name, email, image, etc.). If they are not logged in, it will be null.

  // rendering children on layout page where children is page.js (home page)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        {/* If you’re not logged in, you won’t be able to see the children — instead, the login screen will appear. */}

        {!session && <LoginScreen />}

        {/* If you’re logged in, you’ll see the children (the app content).*/}

        {session && (
          <div className="min-h-screen bg-black px-4 py-8">
            <div className="max-w-4xl mx-auto">
              <Header />
              {children}
              <Toaster />
            </div>
          </div>
        )}
      </body>
    </html>
  );
}

/* 

Now we want to implement authentication , that when we are not loggedIn , 
   
   - there is screen showing u need to Login 
   - when we are loggedIn we can see domains , keywords and tracking and everything


layout.js and page.js are like server components so they are rendered on the server side , so we use backend / server api calls here


*/
